DROP TABLE IF EXISTS file_tags CASCADE;
DROP TABLE IF EXISTS file_links CASCADE;
DROP TABLE IF EXISTS file_version_chunks CASCADE;
DROP TABLE IF EXISTS file_chunks CASCADE;
DROP TABLE IF EXISTS file_versions CASCADE;
DROP TABLE IF EXISTS files CASCADE;
